name: Wily

on:
  pull_request:

jobs:

  evaluate-complexity:
    name: Evaluate Code Complexity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install Wily
        run: pip install wily==1.23.0
      - name: Build cache and diff
        id: wily
        run: |
          wily build singalong/ test/
          DIFF=$(wily diff singalong/ test/ --no-detail -r origin/${{github.event.pull_request.base.ref}})
          echo "$DIFF"

          # Build multiline output
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "::set-output name=diff::$DIFF"
      - name: Find current PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Add Wily PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.findPr.outputs.number && steps.wily.outputs.diff != ''
        with:
          recreate: true
          number: ${{steps.findPr.outputs.number}}
          message: |
            ```
            ${{steps.findPr.outputs.number}}
            ```
      - name: Add Wily PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.findPr.outputs.number && steps.wily.outputs.diff == ''
        with:
          recreate: true
          number: ${{steps.findPr.outputs.number}}
          message: |
            ```
            Wily: No changes in complexity detected.
            ```
